import services from './services'

export default {
  [services.alb]: 'albs',
  [services.apiGatewayResource]: 'apiGatewayResources',
  [services.apiGatewayRestApi]: 'apiGatewayRestApis',
  [services.apiGatewayStage]: 'apiGatewayStages',
  [services.iamGroup]: 'iamGroups',
  [services.iamOpenIdConnectProvider]: 'iamOpenIdConnectProviders',
  [services.iamPasswordPolicy]: 'iamPasswordPolicies',
  [services.iamPolicy]: 'iamPolicies',
  [services.iamRole]: 'iamRoles',
  [services.iamSamlProvider]: 'iamSamlProviders',
  [services.iamServerCertificate]: 'iamServerCertificates',
  [services.iamUser]: 'iamUsers',
  [services.asg]: 'asgs',
  [services.athenaDataCatalog]: 'athenaDataCatalogs',
  [services.cloudfront]: 'cloudfrontDistributions',
  [services.cloudwatchLog]: 'cloudwatchLogs',
  [services.codebuild]: 'codebuilds',
  [services.ec2Instance]: 'ec2Instances',
  [services.eksCluster]: 'eksClusters',
  [services.flowLog]: 'flowLogs',
  [services.guardDutyDetector]: 'guardDutyDetectors',
  [services.nat]: 'natGateway',
  [services.networkInterface]: 'networkInterfaces',
  [services.organization]: 'organizations',
  [services.rdsCluster]: 'rdsClusters',
  [services.rdsDbInstance]: 'rdsDbInstances',
  [services.redshiftCluster]: 'redshiftClusters',
  [services.route53HostedZone]: 'route53HostedZones',
  [services.route53Record]: 'route53Records',
  [services.routeTable]: 'routeTables',
  [services.sageMakerExperiment]: 'sageMakerExperiments',
  [services.sageMakerProject]: 'sageMakerProjects',
  [services.secretsManager]: 'secretsManager',
  [services.sg]: 'securityGroups',
  [services.subnet]: 'subnets',
  [services.transitGatewayAttachment]: 'transitGatewayAttachments',
  [services.vpnConnection]: 'vpnConnections',
}
