export default {
  alb: 'alb',
  cloudwatch: 'cloudwatch',
  ebs: 'ebs',
  ec2Instance: 'ec2Instance',
  eip: 'eip',
  eks: 'eks',
  elb: 'elb',
  igw: 'igw',
  kms: 'kms',
  lambda: 'lambda',
  nat: 'nat',
  sg: 'sg',
  subnet: 'subnet',
  vpc: 'vpc',
  networkInterface: 'network_interface',
}
