export default {
  alb: 'alb',
  apiGatewayResource: 'apiGatewayResource',
  apiGatewayRestApi: 'apiGatewayRestApi',
  apiGatewayStage: 'apiGatewayStage',
  asg: 'asg',
  billing: 'billing',
  cognitoIdentityPool: 'cognitoIdentityPool',
  cognitoUserPool: 'cognitoUserPool',
  cloudwatch: 'cloudwatch',
  ebs: 'ebs',
  ec2Instance: 'ec2Instance',
  eip: 'eip',
  elb: 'elb',
  igw: 'igw',
  kinesisStream: 'kinesisStream',
  kms: 'kms',
  lambda: 'lambda',
  nat: 'nat',
  networkInterface: 'networkInterface',
  route53HostedZone: 'route53HostedZone',
  route53Record: 'route53Record',
  routeTable: 'routeTable',
  sg: 'sg',
  vpc: 'vpc',
  sqs: 'sqs',
  s3: 's3',
}
