export default {
  vpc: 'VpcId',
  port: 'Port',
  name: 'Name',
  type: 'Type',
  http2: 'routing.http2.enabled',
  scheme: 'Scheme',
  lbName: 'LoadBalancerName',
  dnsName: 'DNSName',
  protocol: 'Protocol',
  createdAt: 'CreatedTime',
  accessLogs: 'access_logs.s3.enabled',
  hostedZone: 'CanonicalHostedZoneId',
  ListenerSSL: 'SslPolicy',
  instanceState: 'instance_state',
  availabilityZone: 'availability_zone',
  listenerArn: 'ListenerArn',
  idleTimeout: 'idle_timeout.timeout_seconds',
  ipAddressType: 'IpAddressType',
  loadBalancerArn: 'LoadBalancerArn',
  deletionProtection: 'deletion_protection.enabled',
  dropInvalidHeaderFields: 'routing.http.drop_invalid_header_fields.enabled',
}
