#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 8/12/2021, 11:48:23 AM
#   From: /Users/ckoning/Projects/autocloud/cloudgraph/providers/cloudgraph-provider-aws/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
