#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 8/16/2021, 7:39:21 PM
#   From: /Users/tylerdunkel/autocloud/cloudgraph-provider-aws/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
